name: Tests

on: [push, pull_request]

jobs:
  unit-test:
    name: Unit tests on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v5

      - uses: subosito/flutter-action@v2
      - run: flutter doctor -v

      - name: Install dependencies
        run: flutter pub get

      - name: Code generation
        run: dart run build_runner build

      - name: Verify formatting
        run: |
          dart format --output=none --set-exit-if-changed $(find lib/src -name "*.dart" -not \( -name "*.*freezed.dart" -o -name "*.*g.dart" \) )
          dart format --output=none --set-exit-if-changed $(find test -name "*.dart" -not \( -name "*.*freezed.dart" -o -name "*.*g.dart" \) )

      - name: Analyze project source
        run: flutter analyze

      - name: Run riverpod lint
        run: dart run custom_lint

      - name: Run unit tests
        run: flutter test
